# Generated by Django 4.2.5 on 2023-09-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_caluser_email_alter_eventlocation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_location',
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.ManyToManyField(blank=True, to='events.eventlocation'),
        ),
    ]
