# Generated by Django 4.2.5 on 2023-09-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_event_location_event_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Location Name'),
        ),
    ]
